title:              Hello, I'm Brian
email:              shiyuan_yang@outlook.com
description:        Data Science and Logistics
author:             Brian Yang
baseurl:            ""
url:                "https://laoyuanx.github.io"

# Social Profiles
twitter_username:   
github_username:    laoyuanx
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
